src/main/java/com/function/model/FunctionService.java
package com.function.model;

import java.util.List;

import com.admin.model.AdminVO;

public class FunctionService {
	private Function_interface dao;

	public FunctionService() {
		dao = new FunctionJDBCDAO();
	}

	public FunctionVO addFunction(String adminFname) {
		FunctionVO functionVO = new FunctionVO();
		functionVO.setAdminFunctionName(adminFname);
		dao.insert(functionVO);
		return functionVO;
	}

	public FunctionVO updateFunction(Integer adminFNo, String adminFname) {
		FunctionVO functionVO = new FunctionVO();
		functionVO.setAdminFunction(adminFNo);
		functionVO.setAdminFunctionName(adminFname);
		dao.update(functionVO);
		return functionVO;
	}

	public void deleteFunction(Integer adminFNo) {
		dao.delete(adminFNo);
	}

	public FunctionVO getOneFunction(Integer adminFNo) {
		return dao.findByPrimaryKey(adminFNo);
	}

	public List<FunctionVO> getAll() {
		return dao.getAll();
	}
}

src/main/java/com/function/model/FunctionVO.java
package com.function.model;

public class FunctionVO {
private Integer adminFunction;
private String adminFunctionName;


public Integer getAdminFunction() {
	return adminFunction;
}
public void setAdminFunction(Integer adminFunction) {
	this.adminFunction = adminFunction;
}
public String getAdminFunctionName() {
	return adminFunctionName;
}
public void setAdminFunctionName(String adminFunctionName) {
	this.adminFunctionName = adminFunctionName;
}



}

src/main/java/com/function/model/Function_interface.java
package com.function.model;

import java.util.List;

import com.function.model.FunctionVO;

public interface Function_interface {
	public void insert(FunctionVO functionVO);
    public void update(FunctionVO functionVO);
    public void delete(Integer adminFunction);
    public FunctionVO findByPrimaryKey(Integer adminFunction);
    public List<FunctionVO> getAll();
}

src/main/java/com/function/controller/FunctionServlet.java
package com.function.controller;

import java.io.IOException;
import java.util.LinkedHashMap;
import java.util.Map;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.function.model.*;

@WebServlet("/back-end/function/FunctionServlet")
public class FunctionServlet  extends HttpServlet{

	
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest req, HttpServletResponse res) throws ServletException, IOException {
		
	doPost(req, res);
	}

	@Override
	protected void doPost(HttpServletRequest req, HttpServletResponse res) throws ServletException, IOException {
		req.setCharacterEncoding("UTF-8");
		String action = req.getParameter("action");
		if ("getOne_For_Display".equals(action)) {
//			 Select.jsp請求
			Map<String, String> errorMsgs = new LinkedHashMap<String, String>();
			req.setAttribute("errorMsgs", errorMsgs);
			// 請求參數,錯誤處理
			String eff = req.getParameter("adminFunction");
			// 去除空白後長度為0
			if (eff == null || (eff.trim()).length() == 0) {
				errorMsgs.put("adminFunction","請輸入權限編號");
			}
			// 是否為空字串(非空白)
			if (!errorMsgs.isEmpty()) {
				// 轉發到
				RequestDispatcher fail = req.getRequestDispatcher("/back-end/function/select_page.jsp");
				fail.forward(req, res);
				return;
			}

			Integer adminFunction = null;
			try {
				adminFunction = Integer.valueOf(eff);
			} catch (NumberFormatException e) {
				errorMsgs.put("adminFunction","權限編號不正確");
			}
			if (!errorMsgs.isEmpty()) {
				RequestDispatcher fail = req.getRequestDispatcher("/back-end/function/select_page.jsp");
				fail.forward(req, res);
				return;
			}

			// 驗證過,開始查詢資料
			FunctionService functionSvc = new FunctionService();
			FunctionVO functionVO = functionSvc.getOneFunction(adminFunction);
			if (functionVO == null) {
				errorMsgs.put("adminFunction","查無資料");
			}
			if (!errorMsgs.isEmpty()) {
				RequestDispatcher fail = req.getRequestDispatcher("/back-end/function/select_page.jsp");
				fail.forward(req, res);
				return;
			}

			// 回傳資料
			req.setAttribute("functionVO", functionVO);
			String url = "/back-end/function/listOneFunction.jsp";
			RequestDispatcher successView = req.getRequestDispatcher(url);
			successView.forward(req, res);
		}

		if ("getOne_For_Update".equals(action)) {

			Map<String, String> errorMsgs = new LinkedHashMap<String, String>();
			req.setAttribute("errorMsgs", errorMsgs);
			Integer adminFunction = Integer.valueOf(req.getParameter("adminFunction"));

			FunctionService functionSvc  = new FunctionService();
			FunctionVO functionVO = functionSvc.getOneFunction(adminFunction);

			req.setAttribute("functionVO", functionVO);
			String url = "/back-end/function/update_function_input.jsp";

			RequestDispatcher successView = req.getRequestDispatcher(url);
			successView.forward(req, res);
		}

		if ("update".equals(action)) {
			
			Map<String, String> errorMsgs = new LinkedHashMap<String, String>();
			req.setAttribute("errorMsgs", errorMsgs);

			Integer adminFunction = Integer.valueOf(req.getParameter("adminFunction").trim());
			String adminFunctionName = req.getParameter("adminFunctionName");
		if(adminFunctionName == null || adminFunctionName.trim().length() == 0 ) {
			errorMsgs.put("adminFunctionName","請輸入權限名稱");
		}
			FunctionVO functionVO = new FunctionVO();
			functionVO.setAdminFunction(adminFunction);
			functionVO.setAdminFunctionName(adminFunctionName);

			if (!errorMsgs.isEmpty()) {
				req.setAttribute("functionVO", functionVO);
				RequestDispatcher fail = req.getRequestDispatcher("/back-end/function/update_function_input.jsp");
				fail.forward(req, res);
				return;
			}
			// 修改
			FunctionService functionSvc = new FunctionService();
			// 修改完成
//			
			functionVO = functionSvc.updateFunction(adminFunction, adminFunctionName);

			req.setAttribute("functionVO", functionVO);
			String url = "/back-end/function/listOneFunction.jsp";
			RequestDispatcher successView = req.getRequestDispatcher(url);
			successView.forward(req, res);
		}
		if ("insert".equals(action)) {
			Map<String, String> errorMsgs = new LinkedHashMap<String, String>();
			req.setAttribute("errorMsgs", errorMsgs);
			String adminFunctionName = req.getParameter("adminFunctionName").trim();
			if (adminFunctionName == null || adminFunctionName.trim().length() == 0) {
				errorMsgs.put("adminFunctionName","權限名稱請勿留白");
			}
			
			FunctionVO functionVO =new FunctionVO();
			functionVO.setAdminFunctionName(adminFunctionName);

			if (!errorMsgs.isEmpty()) {
				req.setAttribute("functionVO", functionVO);
				RequestDispatcher fail = req.getRequestDispatcher("/back-end/function/addFunction.jsp");
				fail.forward(req, res);
				return;
			}

			// 新增資料
			FunctionService functionSvc = new FunctionService();
			functionVO = functionSvc.addFunction(adminFunctionName);
//			
			// 完成,轉交
			req.setAttribute("functionVO", functionVO);
			String url = "/back-end/function/listAllFunction.jsp";
			RequestDispatcher successView = req.getRequestDispatcher(url);
			successView.forward(req, res);
		}
		
		if("delete".equals(action)) {
			Map<String, String> errorMsgs = new LinkedHashMap<String, String>();
			req.setAttribute("errorMsgs", errorMsgs);
			
			//接收請求
			Integer adminFunction = Integer.valueOf(req.getParameter("adminFunction"));
			//刪除
			FunctionService functionSvc = new FunctionService();
			functionSvc.deleteFunction(adminFunction);
			//完成,轉交
			String url = "/back-end/function/listAllFunction.jsp";
			RequestDispatcher successView = req.getRequestDispatcher(url);
			successView.forward(req, res);
		}
	}	
}

src/main/webapp/back-end/function/addFunction.jsp
<%@page import="com.access.model.*"%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ page import="java.util.*"%>
<%@ page import="com.function.model.*"%>
<jsp:useBean id="adminSvc" scope="page" class="com.admin.model.AdminService" />
<jsp:useBean id="functionSvc" scope="page" class="com.function.model.FunctionService"/>

<%
Integer adminno = (Integer)session.getAttribute("adminno");

AccessVO accessVO = (AccessVO) request.getAttribute("AccessVO");
%>
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="<%=request.getContextPath()%>/resources/static/css/back-end.css">
<link rel="stylesheet" href="<%=request.getContextPath()%>/resources/static/css/back-endStyle.css">
<title>權限新增資料 </title>

<style>
  table {
	width: 450px;
	margin-top: 1px;
	margin-bottom: 1px;
	margin-left: 30%;
  }
  table, th, td {
    border: 0px solid #CCCCFF;
  }
  th, td {
    padding: 1px;
  }

</style>

</head>
<body>

<%-- <nav><%@include file="/back-end/topNavbar.jsp"%></nav> --%>
<!-- 	<main> -->
<%-- 		<%@include file="/back-end/leftside.jsp"%> --%>
		<section>
			<%-- 錯誤表列 --%>
			<div class="btnTitle">
			<button onclick="location.href='<%=request.getContextPath()%>/back-end/admin/listAlladmin.jsp'" class="btn btn-primary btnIn">回員工查詢</button>
		</div>
		<div class="btnTitle">
			<button onclick="location.href='<%=request.getContextPath()%>/back-end/access/select_page.jsp'" class="btn btn-primary btnIn">查詢權限</button>
		</div>
		<div class="titleBlock">新增員工權限</div>
<FORM METHOD="post" ACTION="<%=request.getContextPath()%>/back-end/access/AccessServlet.do" name="form1">
<table>
	<tr>
		<td>員工姓名:</td>
		<td><input type="${accessVO.adminno ==null? 'TEXT':'hidden'}" name="adminno" size="45" 
			 value="${accessVO.adminno}"  />${accessVO.adminVO.adminName}</td>
	</tr>
	<tr>
		<td>權限:</td>
		
		<td>
		<select class="function" name="adminFunction">
		<c:forEach var="functionVO" items="${functionSvc.all}">
		<option value="${functionVO.adminFunction}">${functionVO.adminFunctionName}</option>
		</c:forEach>
		</select>
		</br><font color="red">${errorMsgs.adminFunction}</font>
		</td>
		
	</tr>


</table>
<br>
<div class="subBlock">
<input type="hidden" name="action" value="insert">
<input type="submit" value="送出新增" class="btn btn-success btnIn"></FORM>
</div>
		</section>
	</main>



</body>

src/main/webapp/back-end/function/listAllFunction.jsp
<%@page import="com.access.model.*"%>
<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ page import="java.util.*"%>
<%@page import="com.function.model.*"%>
<%@ page import="com.admin.model.*"%>
<jsp:useBean id="adminSvc" scope="page" class="com.admin.model.AdminService" />
<jsp:useBean id="functionSvc" scope="page" class="com.function.model.FunctionService" />
<%
AccessService accessSvc = new AccessService();
List<AccessVO> list = accessSvc.getAll();
pageContext.setAttribute("list", list);
%>
<html>
<head>
<title>所有員工資料</title>
<link rel="stylesheet" href="<%=request.getContextPath()%>/resources/static/css/back-end.css">
<link rel="stylesheet" href="<%=request.getContextPath()%>/resources/static/css/back-endStyle.css">
<style>
  table {
	width: 800px;
	margin-top: 5px;
	margin-bottom: 5px;
	margin-left: 10%;
  }
  table, th, td {
    border: 1px solid #CCCCFF;
  }
  th, td {
    padding: 5px;
    text-align: center;
  }
  
  tr:nth-child(even) {
	background-color: rgba(255,255,255,0.4);
}
  
    .btn-warning{
  	margin-top: 15px;
  }
  
  .btnTitle{
  	margin-top: 25px;
  }
  
  .btnSmall{
  	margin-top:0;
  }
</style>

</head>
<body>


		<section>
		<div class="btnTitle">
			<button onclick="location.href='<%=request.getContextPath()%>/back-end/access/select_page.jsp'" class="btn btn-primary btnIn">回員工權限管理首頁</button>
		</div>
		<div class="titleBlock">所有員工權限列表</div>
			<table>
	<tr>
		<th>員工姓名</th>
		<th>權限編號</th>
		<th colspan="2">更改資料</th>
	

	</tr>

	
		
	<c:forEach var="accessVO" items="${list}" >
	
		<tr>
			<td>[${accessVO.adminno}]${accessVO.adminVO.adminName}</td>
			<td>[${accessVO.adminFunction}]${accessVO.functionVO.adminFunctionName}</td>
			<td>
			  <FORM METHOD="post" ACTION="AccessServlet" style="margin-bottom: 0px;">
			     <input type="submit" value="新增" class="btn btn-warning btnIn btnSmall">
			     <input type="hidden" name="adminno"  value="${accessVO.adminno}">
			     <input type="hidden" name="action"	value="go_Insert"></FORM>
			</td>
			<td>
			  <FORM METHOD="post" ACTION="AccessServlet" style="margin-bottom: 0px;">
			     <input type="submit" value="刪除" class="btn btn-danger btnIn btnSmall">
			     <input type="hidden" name="adminFunction"  value="${accessVO.adminFunction}">
			     <input type="hidden" name="action" value="delete"></FORM>
			</td>
		</tr>
	</c:forEach>
</table>
		</section>
	</main>


</body>

src/main/webapp/back-end/function/select_page.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="<%=request.getContextPath()%>/resources/static/css/back-end.css">
<link rel="stylesheet" href="<%=request.getContextPath()%>/resources/static/css/back-endStyle.css">
<title>員工權限首頁</title>
<style>
section{
	text-align: center;
}
</style>

</head>
<body>
<%-- <nav><%@include file="/back-end/topNavbar.jsp"%></nav> --%>
<!-- 	<main> -->
<%-- 		<%@include file="/back-end/leftside.jsp"%> --%>
		<section>
		<div class="btnTitle">
			<button onclick="location.href='<%=request.getContextPath()%>/back-end/admin/listAllEmp.jsp'" class="btn btn-primary btnIn">回查詢員工資料</button>
		</div>
	<div class="titleBlock">員工權限管理首頁</div></br>	
		
  <font color="red">${errorMsgs.fail}</font>
  
  <jsp:useBean id="accessSvc" scope="page" class="com.access.model.AccessService" />
    <jsp:useBean id="functionSvc" scope="page" class="com.function.model.FunctionService" />
     <jsp:useBean id="adminSvc" scope="page" class="com.admin.model.AdminService" />
     	
     <FORM METHOD="post" ACTION="AccessServlet.do" >
       <b>選擇權限編號:</b>
       <select size="1" name="adminFunction">
         <c:forEach var="functionVO" items="${functionSvc.all}" > 
          <option value="${functionVO.adminFunction}">[${functionVO.adminFunction}]-${functionVO.adminFunctionName}
         </c:forEach>   
       </select>
       <input type="hidden" name="action" value="getOne_For_DisplayEffect">
       <input type="submit" value="送出" class="btn btn-info btnIn btnSmall">
    </FORM><br>
  
     <FORM METHOD="post" ACTION="AccessServlet.do" >
       <b>選擇員工名稱:</b>
       <select size="1" name="adminno">
        <c:forEach var="adminVO" items="${adminSvc.all}" > 
          <option value="${adminVO.adminno}">[${adminVO.adminno}]-${adminVO.adminName}
         </c:forEach>   
       </select>
       <input type="hidden" name="action" value="getOne_For_Display">
       <input type="submit" value="送出" class="btn btn-info btnIn btnSmall">
     </FORM><br>
					&ensp;&ensp;
		<button onclick="location.href='<%=request.getContextPath()%>/back-end/access/listAllAccess.jsp'" class="btn btn-dark btnL">查詢所有員工權限</button>	
		</section>
	</main>

</body>
</html>

src/main/webapp/back-end/function/update_function_input.jsp
<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ page import="com.access.model.*"%>
<%
// Emp_effectVO accessVO = (Emp_effectVO) request.getAttribute("accessVO");
%>
<html>
<head>
<link rel="stylesheet" href="<%=request.getContextPath()%>/resources/static/css/back-end.css">
<link rel="stylesheet" href="<%=request.getContextPath()%>/resources/static/css/back-endStyle.css">
<title>權限資料修改</title>

<style>
table {
	width: 450px;
	height: 100px;
	margin-top: 1px;
	margin-bottom: 1px;
	margin-left: 25%;
}

table, th, td {
	border: 0px solid #CCCCFF;
}

th, td {
	padding: 1px;
}

 .btn-warning{
  	margin-top: 15px;
  }
  
  .btnTitle{
  	margin-top: 25px;
  }
</style>

</head>
<body>

<%-- <nav><%@include file="/back-end/topNavbar.jsp"%></nav> --%>
<!-- 	<main> -->
<%-- 		<%@include file="/back-end/leftside.jsp"%> --%>
		<section>
		<div class="btnTitle">
			<button onclick="location.href='<%=request.getContextPath()%>/back-end/access/select_page.jsp'" class="btn btn-primary btnIn">回員工權限管理首頁</button>
		</div>
		<div class="titleBlock">修改員工權限</div>
			<FORM METHOD="post" ACTION="AccessServlet" name="form1">
		<table>
		
			<tr>
				<td>員工編號:</td>
				<td><input type="TEXT" name="adminNo" size="45"
					value="${accessVO.adminNo}" /></td>
			</tr>
			<tr>
				<td>權限帳號:</td>
				<td><input type="TEXT" name="adminFunction" size="45"
					value="${accessVO.adminFunction}" /></td>
			</tr>
			
		</table>

		<br> 
		<div class="subBlock">
		<input type="hidden" name="action" value="insert"> <input
			type="hidden" name="adminNo" value="${accessVO.adminNo}"> 
			<input type="submit" value="送出修改" class="btn btn-success btnIn">
		</div>
	</FORM>
		</section>
	</main>





	

</body>
</html>